export const API_BASE_URL = "http://192.168.1.42:4000";

export const categories = ["All", "Premium", "Square", "Event Bottles"];

export const products = [
  {
    id: 1,
    name: "1000 ML Premium Shape",
    price: 210,
    pcs: 12,
    category: "Premium",
    image: require("../../assets/products/1000mlcircle.png"),
  },
  {
    id: 2,
    name: "500 ML Premium Shape",
    price: 240,
    pcs: 24,
    category: "Premium",
    image: require("../../assets/products/500mlcircle.png"),
  },
  {
    id: 3,
    name: "1000 ML Square Shape",
    price: 150,
    pcs: 12,
    category: "Square",
    image: require("../../assets/products/1000mlsqr.png"),
  },
  {
    id: 4,
    name: "500 ML Square Shape",
    price: 190,
    pcs: 24,
    category: "Square",
    image: require("../../assets/products/500mlsqr.png"),
  },
  {
    id: 5,
    name: "200 ML Square Shape",
    price: 130,
    pcs: 24,
    category: "Square",
    image: require("../../assets/products/200mlsqr.png"),
  },
  {
    id: 6,
    name: "Event Circle Bottle 1",
    price: 210,
    pcs: 12,
    category: "Event Bottles",
    image: require("../../assets/products/eventcircle1.png"),
  },
  {
    id: 7,
    name: "Event Circle Bottle 2",
    price: 210,
    pcs: 12,
    category: "Event Bottles",
    image: require("../../assets/products/eventcircle2.png"),
  },
  {
    id: 8,
    name: "Event Circle Bottle 3",
    price: 210,
    pcs: 12,
    category: "Event Bottles",
    image: require("../../assets/products/eventcircle3.png"),
  },
  {
    id: 9,
    name: "Event Square Bottle 1",
    price: 210,
    pcs: 12,
    category: "Event Bottles",
    image: require("../../assets/products/eventsquare1.png"),
  },
  {
    id: 10,
    name: "Event Square Bottle 2",
    price: 210,
    pcs: 12,
    category: "Event Bottles",
    image: require("../../assets/products/eventsquare2.png"),
  },
  {
    id: 11,
    name: "Event Square Bottle 3",
    price: 210,
    pcs: 12,
    category: "Event Bottles",
    image: require("../../assets/products/eventsquare3.png"),
  },
];
